### PR TITLE
Release v0.10.5

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Review by natario1 — APPROVED** [review]

**Comment by natario1** [comment]
Thanks!

**Comment by vanniktech** [comment]
You would need to create the corresponding Git Tag though.

**Comment by vanniktech** [comment]
@natario1 should this version already been published or does it require something from your side? Either way, I'm unable to get it.

**Comment by natario1** [comment]
It does but publishing to maven central is still down https://status.maven.org/ , I just tried again to publish the snapshot. I can try later again

**Comment by natario1** [comment]
Kind of crazy they couldn't fix it in 8 hours.

**Comment by vanniktech** [comment]
Hmmm, still no luck?

**Comment by natario1** [comment]
No luck yet for release... For now you can pull
- `latest-SNAPSHOT` from `maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")`
- (maybe) `0.10.5` from `maven("https://s01.oss.sonatype.org/content/groups/staging/")`

**Comment by vanniktech** [comment]
Weird. I was able to push a new version of my library just ~45 minutes ago: https://github.com/vanniktech/lint-rules/actions/runs/4230887202/jobs/7348744216

**Comment by natario1** [comment]
Not sure, maybe you are not using the s01 server which is where the problems are. I was able to push yesterday night but the sonatype website to confirm the release, does not work

**Comment by vanniktech** [comment]
Aaaah my plugin uses the API to confirm the release, so it's not using the website: https://github.com/vanniktech/gradle-maven-publish-plugin/tree/main/nexus/src/main/kotlin/com/vanniktech/maven/publish/nexus

**Comment by natario1** [comment]
The API is broken too... Just tried to hit these from terminal, most endpoints but `GET staging/profile_repositories` does not. 

If I knew staging repository ID I could promote from command line. I remember that the visible name in the website was something like profilename-0001 with incremental number. Is that the ID?

**Comment by natario1** [comment]
I think I was able to guess it! it was `comotaliastudios-1013`. Got a 201 response. I think the library will be available soon.

**Comment by vanniktech** [comment]
Amazing!

**Pull request merged**
